services:
    glpi:
        image: chndv/glpi:10.0.17
        hostname: glpi.lan
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "80"
        volumes:
            - glpi-data:/var/www/html/glpi
    db:
        image: mysql:8.4.3
        environment:
            - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data:
    glpi-data:
