services:
    glpi:
        image: chndv/glpi:10.0.17
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PORT}:80"
        volumes:
            - app-files:/var/www/html/glpi/files
            - app-config:/var/www/html/glpi/config
    db:
        image: mysql:8.4.3
        environment:
            - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data:
    app-files:
    app-config: