services:
    glpi:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        restart: on-failure
        deploy:
            
        ports:
            - "8080:80"
        environment:
            - TZ=Europe/Moscow
            - XDG_DATA_HOME=/var/lib/caddy/data
            - XDG_CONFIG_HOME=/var/lib/caddy/config
        volumes:
            - app-files:/var/www/glpi
            - caddy-data:/var/lib/caddy
    db:
        image: mysql:8.4.3
        environment:
            - "MYSQL_ROOT_PASSWORD=password"
        volumes:
            - db-data:/var/lib/mysql
volumes:
    db-data:
    app-files:
    caddy-data:
