services:
    glpi:
        image: glpi:10.0.18-alpine-caddy
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        restart: on-failure
        ports:
            - "80:80"
        environment:
            - TZ=Europe/Moscow
        volumes:
            - app-files:/var/www/glpi
    db:
        image: mysql:8.4.3
        environment:
            - "MYSQL_ROOT_PASSWORD=password"
        volumes:
            - db-data:/var/lib/mysql
volumes:
    db-data:
    app-files:
    app-config:
    app-plugins:
    app-marketplace:
