services:
    glpi:
        image: glpi:10.0.6-alpine
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "80:80"
        env_file: .env
        volumes:
            - app-files:/var/www/glpi/files
            - app-config:/var/www/glpi/config
            - app-plugins:/var/www/glpi/plugins
            - app-marketplace:/var/www/glpi/marketplace
    db:
        image: mysql:8.4.3
        environment:
            - "MYSQL_ROOT_PASSWORD=password"
        volumes:
            - db-data:/var/lib/mysql
volumes:
    db-data:
    app-files:
    app-config:
    app-plugins:
    app-marketplace:
